---
apiVersion: v1
kind: Secret
metadata:
  name: ${{values.namespace}}-${{values.component_id}}-repo
  namespace: suxess-it-admin
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ${{values.destination}}
